# XP SYSTEM
LEVEL_UP_BASE = 200
LEVEL_UP_FACTOR = 150


# MOB XP VALUE
MIGHT_XP_VALUE = 0.5
VITALITY_XP_VALUE = 0.75
HP_XP_VALUE = 0.25
BASE_DAMAGE_XP_VALUE = 1
AVAILABLE_STAT_INCREASE_PER_LEVEL = 1