MAP_WIDTH = 80
MAP_HEIGHT = 60

ROOM_MIN_S_W = 7
ROOM_MAX_S_W = 11
ROOM_MIN_S_H = 3
ROOM_MAX_S_H = 5

MAX_ROOMS = 30
MAX_PLACEMENT_ITERATIONS = 20
MAX_ITERATIONS = 600

CORRIDOR_CHANCES = 0
ROOM_IF_NO_CORRIDOR = 0
ANY_ROOM_MAY_BE_PREVIOUS = 0


# LOOTS AND SPAWNS
MAX_TABLE_ITERATIONS = 5
FREQUENCY_VERY_COMMON = 100
FREQUENCY_COMMON = 70
FREQUENCY_UNCOMMON = 30
FREQUENCY_RARE = 10
FREQUENCY_VERY_RARE = 2

